Repository naturerobots/HSOS-SEP-PlantMap-2022, pull requests merged in 2022-06, with the labels that each got.

#73 feat/crop-image
  vue/package-lock.json
  vue/package.json
  vue/src/assets/base.css
  vue/src/components/ImageCrop.vue
  vue/src/components/SidebarMenu.vue
  vue/src/router/index.ts
  vue/src/views/CropImageView.vue
Labels: frontend

#77 feat: created gardenmap component
  vue/src/components/GardenMap.vue
Labels: frontend, comp: init

#76 feat/integrate leaflet
  vue/package-lock.json
  vue/package.json
  vue/src/assets/marker/marker_green.svg
  vue/src/components/Leaflet/LeafletComp.vue
  vue/src/components/Leaflet/LeafletRotatedComp.vue
  vue/src/components/Leaflet/LeafletRotation.ts
  vue/src/router/index.ts
  vue/src/views/ImageUploadView.vue
Labels: frontend, comp: init

#90 feat/image upload and placing workflow
  vue/package-lock.json
  vue/package.json
  vue/src/components/ImageCrop.vue
  vue/src/components/Leaflet/LeafletRotatedComp.vue
  vue/src/components/Leaflet/LeafletRotation.ts
  vue/src/router/index.ts
Labels: frontend

#91 feat/add a commit message linter
  .commitlintrc.json
  .devcontainer/post-create-setup.sh
  .pre-commit-config.yaml
Labels: type: enhancement

#74 update README to reflect current project status
  README.md
  doc/plant-map-architecture.png
  doc/plant-map-logo.png
  doc/seerep.png
Labels: type: documentation

#95 feat/header create
  vue/src/App.vue
  vue/src/assets/base.css
  vue/src/components/BaseMap.vue
  vue/src/components/HeaderBar.vue
  vue/src/components/SensorComp.vue
  vue/src/components/WeatherComp.vue
  vue/src/views/Crops3dView.vue
  vue/src/views/CropsView.vue
  vue/src/views/DashboardView.vue
Labels: frontend

#96 feat/leaflet functions
  vue/package-lock.json
  vue/package.json
  vue/src/assets/marker/sensor_icon.svg
  vue/src/components/BaseMap.vue
  vue/src/components/CropsMap.vue
  vue/src/components/GardenMap.vue
  vue/src/components/Leaflet/LeafletComp.vue
  vue/src/components/Leaflet/LeafletRotatedComp.vue
Labels: frontend

#97 feat/display sensors
  vue/src/App.vue
  vue/src/assets/marker/sensor_icon.svg
  vue/src/assets/mocks/sensorMockData.json
  vue/src/components/BaseMap.vue
  vue/src/components/GardenMap.vue
  vue/src/components/SensorComp.vue
  vue/src/types/sensor.ts
  vue/src/views/DashboardView.vue
Labels: frontend

#103 feat/weather add chart to component
  .devcontainer/.vscode/settings.json
  vue/package-lock.json
  vue/package.json
  vue/src/App.vue
  vue/src/components/SidebarMenu.vue
  vue/src/components/Weather/ChartHourlyWind.vue
  vue/src/components/Weather/ChartSettings.ts
  vue/src/components/Weather/LineChart.vue
  vue/src/components/Weather/WeatherChartComp.vue
  vue/src/components/Weather/WeatherComp.vue
  vue/src/components/Weather/WeatherForecast.vue
  vue/src/components/WeatherComp.vue
  vue/src/router/index.ts
  vue/src/services/geoDataAPI.ts
  vue/src/services/openWeatherApi.ts
  vue/src/services/weatherDataAPI.ts
  vue/src/stores/weatherDataStore.ts
  vue/src/stores/weatherStore.ts
  vue/src/types/geoData.ts
  vue/src/types/weather.ts
  vue/src/types/weatherData.ts
  vue/src/views/DashboardView.vue
  vue/src/views/WeatherCharts.vue
Labels: frontend

#124 feat/widget manager
  vue/src/assets/base.css
  vue/src/components/header/HeaderBar.vue
  vue/src/components/header/widget/WidgetComp.vue
  vue/src/stores/userStore.ts
  vue/src/types/user.ts
  vue/src/types/widgetOption.ts
  vue/src/views/Crops3dView.vue
  vue/src/views/CropsView.vue
  vue/src/views/DashboardView.vue
Labels: frontend

#125 feat/redesign imagecrop and weather comp
  vue/package-lock.json
  vue/package.json
  vue/src/components/ImageCrop.vue
  vue/src/components/ImageCropQuasar.vue
  vue/src/components/SidebarMenuQuasar.vue
  vue/src/components/Weather/WeatherComp.vue
  vue/src/components/header/HeaderBar.vue
  vue/src/components/weather/ChartHourlyWind.vue
  vue/src/components/weather/ChartSettings.ts
  vue/src/components/weather/LineChart.vue
  vue/src/components/weather/WeatherChartComp.vue
  vue/src/components/weather/WeatherComp.vue
  vue/src/components/weather/WeatherForecast.vue
  vue/src/main.ts
  vue/src/stores/weatherDataStore.ts
  vue/src/views/CropImageView.vue
  vue/src/views/DashboardView.vue
  vue/src/views/WeatherCharts.vue
  vue/tailwind.config.cjs
Labels: frontend

#140 feat/login and register design
  vue/src/App.vue
  vue/src/assets/base.css
  vue/src/assets/img/logo_with_text.svg
  vue/src/components/login/LoginForm.vue
  vue/src/components/register/RegisterForm.vue
  vue/src/views/LoginView.vue
  vue/src/views/RegisterView.vue
Labels: frontend, comp: style

#143 Feat/3d
  Makefile
  django/config/settings.py
  django/config/urls.py
  django/restapi/tasks.py
Labels: backend

#147 feat/authentication in vue
  vue/src/router/index.ts
  vue/src/stores/userStore.ts
  vue/src/types/user.ts
Labels: frontend

#149 feat/authentication for login
  vue/src/components/login/LoginForm.vue
  vue/src/services/userApi.ts
  vue/src/stores/userStore.ts
Labels: frontend, comp: api

#139 Feat/interaction table map
  vue/src/App.vue
  vue/src/assets/base.css
  vue/src/components/CropsMap.vue
  vue/src/components/CropsTable.vue
  vue/src/main.ts
  vue/src/services/cropsApi.ts
  vue/src/views/Crops3dView.vue
  vue/src/views/CropsView.vue
Labels: frontend

#150 feat/refactor imageupload and change tilelayer
  vue/package-lock.json
  vue/src/App.vue
  vue/src/components/BaseMap.vue
  vue/src/components/CropsMap.vue
  vue/src/components/GardenMap.vue
  vue/src/components/ImageCropQuasar.vue
  vue/src/components/SidebarMenuQuasar.vue
  vue/src/components/header/HeaderBar.vue
  vue/src/components/leaflet/LeafletComp.vue
  vue/src/components/leaflet/LeafletRotatedComp.vue
  vue/src/components/leaflet/LeafletRotation.ts
  vue/src/views/CropImageView.vue
  vue/src/views/Crops3dView.vue
  vue/src/views/CropsView.vue
  vue/src/views/DashboardView.vue
  vue/src/views/ImageUploadView.vue
Labels: frontend, comp: style, comp: refactor

#156 feat/add vite env variables and modes
  vue/.env
  vue/.env.development
  vue/.env.production
  vue/env.d.ts
  vue/index.html
  vue/src/router/index.ts
  vue/src/services/geoDataAPI.ts
  vue/src/services/weatherDataAPI.ts
  vue/tsconfig.json
Labels: type: enhancement, frontend

#165 feat/revision of the entire layout
  vue/src/App.vue
  vue/src/components/ImageCrop.vue
  vue/src/components/SensorComp.vue
  vue/src/components/SensorStatus.vue
  vue/src/components/SidebarMenu.vue
  vue/src/components/header/HeaderBar.vue
  vue/src/components/image-crop/ImageCrop.vue
  vue/src/components/layout/BaseLayout.vue
  vue/src/components/layout/SplitLayout.vue
  vue/src/components/leaflet/LeafletRotatedComp.vue
  vue/src/components/leaflet/LeafletRotation.ts
  vue/src/components/map/BaseMap.vue
  vue/src/components/map/CropsMap.vue
  vue/src/components/map/GardenMap.vue
  vue/src/components/sensor/SensorComp.vue
  vue/src/components/sidebar/SidebarMenu.vue
  vue/src/components/table/CropsTable.vue
  vue/src/components/weather/ChartHourlyWind.vue
  vue/src/router/index.ts
  vue/src/views/CropImageView.vue
  vue/src/views/Crops3dView.vue
  vue/src/views/CropsView.vue
  vue/src/views/DashboardView.vue
  vue/src/views/ImageUploadView.vue
  vue/src/views/LoginView.vue
  vue/src/views/RegisterView.vue
  vue/src/views/WeatherCharts.vue
Labels: frontend, comp: style
